export const INCREMENT_COUNTER = "INCREMENT_COUNTER"
export const DECREMENT_COUNTER = "DECREMENT_COUNTER"

export const MEDICINE_GET = "MEDICINE_GET"
export const MEDICINE_ADD = "MEDICINE_ADD"
export const MEDICINES_UPDATE = "MEDICINES_UPDATE"
export const MEDICINES_DELETE = "MEDICINES_DELETE"

export const MEDICINE_LOADING = "MEDICINE_LOADING"
export const MEDICINE_ERROR = "MEDICINE_ERROR"

export const EMPLOYEE_GET = "EMPLOYEE_GET"
export const EMPLOYEE_ADD = "EMPLOYEE_ADD"
export const EMPLOYEE_UPDATE = "EMPLOYEE_UPDATE"
export const EMPLOYEE_DELETE = "EMPLOYEE_DELETE"


export const THEME_TOGGLE = "THEME_TOGGLE"